dict = {
    "gameId": 3579650929,
    "platformId": "NA1",
    "gameCreation": 1600397242551,
    "gameDuration": 3015,
    "queueId": 1020,
    "mapId": 11,
    "seasonId": 13,
    "gameVersion": "10.19.335.4706",
    "gameMode": "ONEFORALL",
    "gameType": "MATCHED_GAME",
    "teams": [
        {
            "teamId": 100,
            "win": "Win",
            "firstBlood": true,
            "firstTower": true,
            "firstInhibitor": false,
            "firstBaron": false,
            "firstDragon": true,
            "firstRiftHerald": false,
            "towerKills": 9,
            "inhibitorKills": 1,
            "baronKills": 0,
            "dragonKills": 3,
            "vilemawKills": 0,
            "riftHeraldKills": 0,
            "dominionVictoryScore": 0,
            "bans": [
                {
                    "championId": 157,
                    "pickTurn": 1
                },
                {
                    "championId": 84,
                    "pickTurn": 2
                },
                {
                    "championId": 31,
                    "pickTurn": 3
                },
                {
                    "championId": 27,
                    "pickTurn": 4
                },
                {
                    "championId": 350,
                    "pickTurn": 5
                }
            ]
        },
        {
            "teamId": 200,
            "win": "Fail",
            "firstBlood": false,
            "firstTower": false,
            "firstInhibitor": true,
            "firstBaron": false,
            "firstDragon": false,
            "firstRiftHerald": false,
            "towerKills": 11,
            "inhibitorKills": 5,
            "baronKills": 0,
            "dragonKills": 1,
            "vilemawKills": 0,
            "riftHeraldKills": 0,
            "dominionVictoryScore": 0,
            "bans": [
                {
                    "championId": 81,
                    "pickTurn": 6
                },
                {
                    "championId": 28,
                    "pickTurn": 7
                },
                {
                    "championId": 157,
                    "pickTurn": 8
                },
                {
                    "championId": 777,
                    "pickTurn": 9
                },
                {
                    "championId": 120,
                    "pickTurn": 10
                }
            ]
        }
    ],
    "participants": [
        {
            "participantId": 1,
            "teamId": 100,
            "championId": 63,
            "spell1Id": 12,
            "spell2Id": 4,
            "stats": {
                "participantId": 1,
                "win": true,
                "item0": 3285,
                "item1": 3905,
                "item2": 3135,
                "item3": 3020,
                "item4": 3151,
                "item5": 3089,
                "item6": 3363,
                "kills": 12,
                "deaths": 12,
                "assists": 18,
                "largestKillingSpree": 3,
                "largestMultiKill": 2,
                "killingSprees": 4,
                "longestTimeSpentLiving": 430,
                "doubleKills": 2,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 240309,
                "magicDamageDealt": 224530,
                "physicalDamageDealt": 11471,
                "trueDamageDealt": 4307,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 53387,
                "magicDamageDealtToChampions": 49831,
                "physicalDamageDealtToChampions": 2066,
                "trueDamageDealtToChampions": 1489,
                "totalHeal": 2780,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 14380,
                "damageDealtToObjectives": 6583,
                "damageDealtToTurrets": 2693,
                "visionScore": 62,
                "timeCCingOthers": 56,
                "totalDamageTaken": 33299,
                "magicalDamageTaken": 27019,
                "physicalDamageTaken": 5214,
                "trueDamageTaken": 1065,
                "goldEarned": 24949,
                "goldSpent": 18875,
                "turretKills": 2,
                "inhibitorKills": 0,
                "totalMinionsKilled": 163,
                "neutralMinionsKilled": 44,
                "neutralMinionsKilledTeamJungle": 32,
                "neutralMinionsKilledEnemyJungle": 4,
                "totalTimeCrowdControlDealt": 178,
                "champLevel": 18,
                "visionWardsBoughtInGame": 3,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 21,
                "wardsKilled": 3,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 6,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8112,
                "perk0Var1": 2479,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8143,
                "perk1Var1": 24,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8138,
                "perk2Var1": 30,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8106,
                "perk3Var1": 5,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8236,
                "perk4Var1": 120,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8224,
                "perk5Var1": 1659,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8200,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 1,
                "creepsPerMinDeltas": {
                    "10-20": 3.1,
                    "0-10": 4.2,
                    "30-end": 2.9499999999999997,
                    "20-30": 3.0999999999999996
                },
                "xpPerMinDeltas": {
                    "10-20": 699.4000000000001,
                    "0-10": 729.3,
                    "30-end": 749.95,
                    "20-30": 883.7
                },
                "goldPerMinDeltas": {
                    "10-20": 420.4,
                    "0-10": 379.4,
                    "30-end": 532.4,
                    "20-30": 514.9
                },
                "csDiffPerMinDeltas": {
                    "10-20": 1.9,
                    "0-10": 2,
                    "30-end": 1.9499999999999997,
                    "20-30": 2
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -92.89999999999998,
                    "0-10": 38.20000000000002,
                    "30-end": -7.650000000000006,
                    "20-30": 153.2
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 700.3,
                    "0-10": 456,
                    "30-end": 796.4,
                    "20-30": 580.8
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -1314,
                    "0-10": -323.5,
                    "30-end": -1649.85,
                    "20-30": -1904.5
                },
                "role": "SOLO",
                "lane": "TOP"
            }
        },
        {
            "participantId": 2,
            "teamId": 100,
            "championId": 63,
            "spell1Id": 6,
            "spell2Id": 4,
            "stats": {
                "participantId": 2,
                "win": true,
                "item0": 3065,
                "item1": 3146,
                "item2": 3001,
                "item3": 3111,
                "item4": 3116,
                "item5": 3194,
                "item6": 3340,
                "kills": 12,
                "deaths": 12,
                "assists": 27,
                "largestKillingSpree": 6,
                "largestMultiKill": 1,
                "killingSprees": 3,
                "longestTimeSpentLiving": 461,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 181838,
                "magicDamageDealt": 160559,
                "physicalDamageDealt": 18844,
                "trueDamageDealt": 2433,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 58496,
                "magicDamageDealtToChampions": 53087,
                "physicalDamageDealtToChampions": 3835,
                "trueDamageDealtToChampions": 1573,
                "totalHeal": 21281,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 71029,
                "damageDealtToObjectives": 12600,
                "damageDealtToTurrets": 3264,
                "visionScore": 27,
                "timeCCingOthers": 141,
                "totalDamageTaken": 61874,
                "magicalDamageTaken": 36155,
                "physicalDamageTaken": 18511,
                "trueDamageTaken": 7206,
                "goldEarned": 23752,
                "goldSpent": 21700,
                "turretKills": 3,
                "inhibitorKills": 1,
                "totalMinionsKilled": 95,
                "neutralMinionsKilled": 7,
                "neutralMinionsKilledTeamJungle": 3,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 1558,
                "champLevel": 18,
                "visionWardsBoughtInGame": 2,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 11,
                "wardsKilled": 3,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 6,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8128,
                "perk0Var1": 2573,
                "perk0Var2": 42,
                "perk0Var3": 0,
                "perk1": 8139,
                "perk1Var1": 2746,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8138,
                "perk2Var1": 30,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8135,
                "perk3Var1": 5637,
                "perk3Var2": 5,
                "perk3Var3": 0,
                "perk4": 8237,
                "perk4Var1": 937,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8224,
                "perk5Var1": 1668,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8200,
                "statPerk0": 5007,
                "statPerk1": 5008,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 2,
                "creepsPerMinDeltas": {
                    "10-20": 2,
                    "0-10": 2.8,
                    "30-end": 1.5499999999999998,
                    "20-30": 1.6
                },
                "xpPerMinDeltas": {
                    "10-20": 756.5999999999999,
                    "0-10": 555.5,
                    "30-end": 901.35,
                    "20-30": 904
                },
                "goldPerMinDeltas": {
                    "10-20": 425.9,
                    "0-10": 307.1,
                    "30-end": 530.7,
                    "20-30": 470.4
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1360.6,
                    "0-10": 740.9000000000001,
                    "30-end": 1388.45,
                    "20-30": 1295.6999999999998
                },
                "role": "NONE",
                "lane": "JUNGLE"
            }
        },
        {
            "participantId": 3,
            "teamId": 100,
            "championId": 63,
            "spell1Id": 14,
            "spell2Id": 4,
            "stats": {
                "participantId": 3,
                "win": true,
                "item0": 3907,
                "item1": 3102,
                "item2": 3285,
                "item3": 3089,
                "item4": 3165,
                "item5": 3151,
                "item6": 3340,
                "kills": 13,
                "deaths": 23,
                "assists": 26,
                "largestKillingSpree": 2,
                "largestMultiKill": 2,
                "killingSprees": 2,
                "longestTimeSpentLiving": 171,
                "doubleKills": 1,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 256660,
                "magicDamageDealt": 226022,
                "physicalDamageDealt": 16304,
                "trueDamageDealt": 14332,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 69879,
                "magicDamageDealtToChampions": 63308,
                "physicalDamageDealtToChampions": 3503,
                "trueDamageDealtToChampions": 3067,
                "totalHeal": 8660,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 30219,
                "damageDealtToObjectives": 3593,
                "damageDealtToTurrets": 3593,
                "visionScore": 10,
                "timeCCingOthers": 68,
                "totalDamageTaken": 66111,
                "magicalDamageTaken": 50541,
                "physicalDamageTaken": 11628,
                "trueDamageTaken": 3941,
                "goldEarned": 25950,
                "goldSpent": 29000,
                "turretKills": 2,
                "inhibitorKills": 0,
                "totalMinionsKilled": 145,
                "neutralMinionsKilled": 20,
                "neutralMinionsKilledTeamJungle": 12,
                "neutralMinionsKilledEnemyJungle": 8,
                "totalTimeCrowdControlDealt": 398,
                "champLevel": 18,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 6,
                "wardsKilled": 0,
                "firstBloodKill": true,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 6,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8229,
                "perk0Var1": 4133,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8275,
                "perk1Var1": 22,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8233,
                "perk2Var1": 19,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8237,
                "perk3Var1": 724,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8139,
                "perk4Var1": 3968,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8106,
                "perk5Var1": 5,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8100,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 3,
                "creepsPerMinDeltas": {
                    "10-20": 2.7,
                    "0-10": 3.2,
                    "30-end": 3.25,
                    "20-30": 2.1
                },
                "xpPerMinDeltas": {
                    "10-20": 761.6,
                    "0-10": 529.4,
                    "30-end": 791.2,
                    "20-30": 736
                },
                "goldPerMinDeltas": {
                    "10-20": 529.6,
                    "0-10": 489.2,
                    "30-end": 475.55,
                    "20-30": 514.7
                },
                "csDiffPerMinDeltas": {
                    "10-20": 1.1,
                    "0-10": 0.8500000000000001,
                    "30-end": 2.725,
                    "20-30": -0.29999999999999993
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 53.19999999999993,
                    "0-10": 34.900000000000006,
                    "30-end": 175.975,
                    "20-30": 83.2000000000001
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1325.4,
                    "0-10": 586.7,
                    "30-end": 1604,
                    "20-30": 1491
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -384.75,
                    "0-10": -427.75000000000006,
                    "30-end": -645.3,
                    "20-30": -363.2500000000001
                },
                "role": "DUO",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 4,
            "teamId": 100,
            "championId": 63,
            "spell1Id": 14,
            "spell2Id": 4,
            "stats": {
                "participantId": 4,
                "win": true,
                "item0": 3116,
                "item1": 3165,
                "item2": 3020,
                "item3": 3151,
                "item4": 3089,
                "item5": 3135,
                "item6": 3340,
                "kills": 18,
                "deaths": 14,
                "assists": 31,
                "largestKillingSpree": 5,
                "largestMultiKill": 2,
                "killingSprees": 5,
                "longestTimeSpentLiving": 429,
                "doubleKills": 4,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 337896,
                "magicDamageDealt": 316005,
                "physicalDamageDealt": 17501,
                "trueDamageDealt": 4389,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 79577,
                "magicDamageDealtToChampions": 72241,
                "physicalDamageDealtToChampions": 3235,
                "trueDamageDealtToChampions": 4100,
                "totalHeal": 6031,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 26746,
                "damageDealtToObjectives": 13260,
                "damageDealtToTurrets": 3800,
                "visionScore": 29,
                "timeCCingOthers": 101,
                "totalDamageTaken": 52910,
                "magicalDamageTaken": 40797,
                "physicalDamageTaken": 10090,
                "trueDamageTaken": 2022,
                "goldEarned": 27406,
                "goldSpent": 24250,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 162,
                "neutralMinionsKilled": 10,
                "neutralMinionsKilledTeamJungle": 6,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 979,
                "champLevel": 18,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 16,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": true,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 6,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8229,
                "perk0Var1": 4698,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8226,
                "perk1Var1": 250,
                "perk1Var2": 1756,
                "perk1Var3": 0,
                "perk2": 8210,
                "perk2Var1": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8236,
                "perk3Var1": 120,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8138,
                "perk4Var1": 30,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8105,
                "perk5Var1": 16,
                "perk5Var2": 5,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8100,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 4,
                "creepsPerMinDeltas": {
                    "10-20": 3,
                    "0-10": 2.1,
                    "30-end": 4.85,
                    "20-30": 1.4
                },
                "xpPerMinDeltas": {
                    "10-20": 1019.1,
                    "0-10": 689.5,
                    "30-end": 933.15,
                    "20-30": 853.6
                },
                "goldPerMinDeltas": {
                    "10-20": 615.2,
                    "0-10": 449.6,
                    "30-end": 535.7,
                    "20-30": 494
                },
                "csDiffPerMinDeltas": {
                    "10-20": 1.1,
                    "0-10": 0.8500000000000001,
                    "30-end": 2.725,
                    "20-30": -0.29999999999999993
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 53.19999999999993,
                    "0-10": 34.900000000000006,
                    "30-end": 175.975,
                    "20-30": 83.2000000000001
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1083.8,
                    "0-10": 371.1,
                    "30-end": 1096.1,
                    "20-30": 1643.9
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -384.75,
                    "0-10": -427.75000000000006,
                    "30-end": -645.3,
                    "20-30": -363.2500000000001
                },
                "role": "DUO",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 5,
            "teamId": 100,
            "championId": 63,
            "spell1Id": 4,
            "spell2Id": 11,
            "stats": {
                "participantId": 5,
                "win": true,
                "item0": 3009,
                "item1": 3151,
                "item2": 3116,
                "item3": 3165,
                "item4": 3135,
                "item5": 3194,
                "item6": 3340,
                "kills": 15,
                "deaths": 13,
                "assists": 23,
                "largestKillingSpree": 5,
                "largestMultiKill": 2,
                "killingSprees": 3,
                "longestTimeSpentLiving": 615,
                "doubleKills": 1,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 395151,
                "magicDamageDealt": 357625,
                "physicalDamageDealt": 17208,
                "trueDamageDealt": 20317,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 88259,
                "magicDamageDealtToChampions": 85362,
                "physicalDamageDealtToChampions": 2257,
                "trueDamageDealtToChampions": 640,
                "totalHeal": 31166,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 54727,
                "damageDealtToObjectives": 37383,
                "damageDealtToTurrets": 3540,
                "visionScore": 38,
                "timeCCingOthers": 113,
                "totalDamageTaken": 77693,
                "magicalDamageTaken": 50308,
                "physicalDamageTaken": 22912,
                "trueDamageTaken": 4472,
                "goldEarned": 27902,
                "goldSpent": 17625,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 154,
                "neutralMinionsKilled": 92,
                "neutralMinionsKilledTeamJungle": 51,
                "neutralMinionsKilledEnemyJungle": 22,
                "totalTimeCrowdControlDealt": 1315,
                "champLevel": 18,
                "visionWardsBoughtInGame": 1,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 20,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 6,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8112,
                "perk0Var1": 3950,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8139,
                "perk1Var1": 2941,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8136,
                "perk2Var1": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8135,
                "perk3Var1": 19965,
                "perk3Var2": 5,
                "perk3Var3": 0,
                "perk4": 8009,
                "perk4Var1": 8193,
                "perk4Var2": 500,
                "perk4Var3": 0,
                "perk5": 8014,
                "perk5Var1": 1792,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8000,
                "statPerk0": 5007,
                "statPerk1": 5002,
                "statPerk2": 5003
            },
            "timeline": {
                "participantId": 5,
                "creepsPerMinDeltas": {
                    "10-20": 2.9000000000000004,
                    "0-10": 1.7000000000000002,
                    "30-end": 4.05,
                    "20-30": 2.7
                },
                "xpPerMinDeltas": {
                    "10-20": 993.4,
                    "0-10": 502.8,
                    "30-end": 979.8000000000001,
                    "20-30": 1108.9
                },
                "goldPerMinDeltas": {
                    "10-20": 731,
                    "0-10": 374.70000000000005,
                    "30-end": 442.5,
                    "20-30": 689.0999999999999
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1309.6,
                    "0-10": 591.5,
                    "30-end": 2160.85,
                    "20-30": 1504.1
                },
                "role": "NONE",
                "lane": "JUNGLE"
            }
        },
        {
            "participantId": 6,
            "teamId": 200,
            "championId": 12,
            "spell1Id": 12,
            "spell2Id": 4,
            "stats": {
                "participantId": 6,
                "win": false,
                "item0": 3190,
                "item1": 3194,
                "item2": 3001,
                "item3": 3107,
                "item4": 3083,
                "item5": 3111,
                "item6": 3364,
                "kills": 7,
                "deaths": 10,
                "assists": 35,
                "largestKillingSpree": 3,
                "largestMultiKill": 1,
                "killingSprees": 1,
                "longestTimeSpentLiving": 904,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 107123,
                "magicDamageDealt": 70725,
                "physicalDamageDealt": 28152,
                "trueDamageDealt": 8245,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 37430,
                "magicDamageDealtToChampions": 30560,
                "physicalDamageDealtToChampions": 6158,
                "trueDamageDealtToChampions": 711,
                "totalHeal": 34325,
                "totalUnitsHealed": 5,
                "damageSelfMitigated": 239030,
                "damageDealtToObjectives": 10611,
                "damageDealtToTurrets": 7965,
                "visionScore": 30,
                "timeCCingOthers": 105,
                "totalDamageTaken": 101716,
                "magicalDamageTaken": 79715,
                "physicalDamageTaken": 18653,
                "trueDamageTaken": 3346,
                "goldEarned": 21324,
                "goldSpent": 25590,
                "turretKills": 2,
                "inhibitorKills": 1,
                "totalMinionsKilled": 65,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 243,
                "champLevel": 18,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 11,
                "wardsKilled": 2,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": true,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 6,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8437,
                "perk0Var1": 2225,
                "perk0Var2": 1965,
                "perk0Var3": 0,
                "perk1": 8446,
                "perk1Var1": 4416,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8444,
                "perk2Var1": 4942,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8453,
                "perk3Var1": 4696,
                "perk3Var2": 591,
                "perk3Var3": 0,
                "perk4": 8234,
                "perk4Var1": 23393,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8236,
                "perk5Var1": 120,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8200,
                "statPerk0": 5008,
                "statPerk1": 5002,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 6,
                "creepsPerMinDeltas": {
                    "10-20": 1.2,
                    "0-10": 2.2,
                    "30-end": 1,
                    "20-30": 1.1
                },
                "xpPerMinDeltas": {
                    "10-20": 792.3,
                    "0-10": 691.1,
                    "30-end": 757.6,
                    "20-30": 730.5
                },
                "goldPerMinDeltas": {
                    "10-20": 480.4,
                    "0-10": 419.9,
                    "30-end": 357.45,
                    "20-30": 416.8
                },
                "csDiffPerMinDeltas": {
                    "10-20": -1.9,
                    "0-10": -2,
                    "30-end": -1.9499999999999997,
                    "20-30": -2
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 92.89999999999998,
                    "0-10": -38.20000000000002,
                    "30-end": 7.650000000000006,
                    "20-30": -153.2
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 2014.3000000000002,
                    "0-10": 779.5,
                    "30-end": 2446.25,
                    "20-30": 2485.3
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 1314,
                    "0-10": 323.5,
                    "30-end": 1649.85,
                    "20-30": 1904.5
                },
                "role": "SOLO",
                "lane": "TOP"
            }
        },
        {
            "participantId": 7,
            "teamId": 200,
            "championId": 12,
            "spell1Id": 4,
            "spell2Id": 14,
            "stats": {
                "participantId": 7,
                "win": false,
                "item0": 3812,
                "item1": 3124,
                "item2": 3091,
                "item3": 3025,
                "item4": 3117,
                "item5": 3072,
                "item6": 3340,
                "kills": 17,
                "deaths": 14,
                "assists": 17,
                "largestKillingSpree": 4,
                "largestMultiKill": 1,
                "killingSprees": 4,
                "longestTimeSpentLiving": 408,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 268943,
                "magicDamageDealt": 205858,
                "physicalDamageDealt": 54436,
                "trueDamageDealt": 8649,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 51860,
                "magicDamageDealtToChampions": 39890,
                "physicalDamageDealtToChampions": 6411,
                "trueDamageDealtToChampions": 5558,
                "totalHeal": 31811,
                "totalUnitsHealed": 5,
                "damageSelfMitigated": 143090,
                "damageDealtToObjectives": 7273,
                "damageDealtToTurrets": 4552,
                "visionScore": 54,
                "timeCCingOthers": 87,
                "totalDamageTaken": 78694,
                "magicalDamageTaken": 58280,
                "physicalDamageTaken": 18222,
                "trueDamageTaken": 2191,
                "goldEarned": 28291,
                "goldSpent": 35933,
                "turretKills": 4,
                "inhibitorKills": 3,
                "totalMinionsKilled": 168,
                "neutralMinionsKilled": 55,
                "neutralMinionsKilledTeamJungle": 32,
                "neutralMinionsKilledEnemyJungle": 12,
                "totalTimeCrowdControlDealt": 472,
                "champLevel": 18,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 21,
                "wardsKilled": 12,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": true,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 6,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8112,
                "perk0Var1": 4164,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8139,
                "perk1Var1": 2630,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8138,
                "perk2Var1": 30,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8106,
                "perk3Var1": 5,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8321,
                "perk4Var1": 5,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8352,
                "perk5Var1": 211,
                "perk5Var2": 1142,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8300,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 7,
                "creepsPerMinDeltas": {
                    "10-20": 2.9,
                    "0-10": 3.2,
                    "30-end": 3.6999999999999997,
                    "20-30": 3.3
                },
                "xpPerMinDeltas": {
                    "10-20": 835.1999999999999,
                    "0-10": 626.5,
                    "30-end": 825.6999999999999,
                    "20-30": 928.9000000000001
                },
                "goldPerMinDeltas": {
                    "10-20": 541,
                    "0-10": 578.8,
                    "30-end": 493.8,
                    "20-30": 621.3
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1458.5,
                    "0-10": 830.8,
                    "30-end": 1806.0500000000002,
                    "20-30": 1968
                },
                "role": "NONE",
                "lane": "JUNGLE"
            }
        },
        {
            "participantId": 8,
            "teamId": 200,
            "championId": 12,
            "spell1Id": 14,
            "spell2Id": 4,
            "stats": {
                "participantId": 8,
                "win": false,
                "item0": 3100,
                "item1": 3089,
                "item2": 3907,
                "item3": 3285,
                "item4": 3089,
                "item5": 3089,
                "item6": 3340,
                "kills": 25,
                "deaths": 17,
                "assists": 16,
                "largestKillingSpree": 6,
                "largestMultiKill": 3,
                "killingSprees": 6,
                "longestTimeSpentLiving": 581,
                "doubleKills": 2,
                "tripleKills": 1,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 235525,
                "magicDamageDealt": 194068,
                "physicalDamageDealt": 25067,
                "trueDamageDealt": 16389,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 77334,
                "magicDamageDealtToChampions": 67477,
                "physicalDamageDealtToChampions": 5410,
                "trueDamageDealtToChampions": 4446,
                "totalHeal": 28118,
                "totalUnitsHealed": 5,
                "damageSelfMitigated": 94323,
                "damageDealtToObjectives": 23542,
                "damageDealtToTurrets": 8199,
                "visionScore": 48,
                "timeCCingOthers": 86,
                "totalDamageTaken": 73213,
                "magicalDamageTaken": 58067,
                "physicalDamageTaken": 13567,
                "trueDamageTaken": 1579,
                "goldEarned": 29222,
                "goldSpent": 31325,
                "turretKills": 1,
                "inhibitorKills": 1,
                "totalMinionsKilled": 146,
                "neutralMinionsKilled": 10,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 255,
                "champLevel": 18,
                "visionWardsBoughtInGame": 1,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 21,
                "wardsKilled": 5,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 6,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8112,
                "perk0Var1": 5947,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8143,
                "perk1Var1": 2418,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8138,
                "perk2Var1": 30,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8105,
                "perk3Var1": 16,
                "perk3Var2": 5,
                "perk3Var3": 0,
                "perk4": 8009,
                "perk4Var1": 9129,
                "perk4Var2": 500,
                "perk4Var3": 0,
                "perk5": 8014,
                "perk5Var1": 2019,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8000,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 8,
                "creepsPerMinDeltas": {
                    "10-20": 3.4,
                    "0-10": 4.6,
                    "30-end": 2.7,
                    "20-30": 1.2
                },
                "xpPerMinDeltas": {
                    "10-20": 875.3,
                    "0-10": 788.9,
                    "30-end": 767.0999999999999,
                    "20-30": 701.0999999999999
                },
                "goldPerMinDeltas": {
                    "10-20": 828,
                    "0-10": 433.3,
                    "30-end": 541.65,
                    "20-30": 477.2
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1734.5,
                    "0-10": 664,
                    "30-end": 1608.5500000000002,
                    "20-30": 1705.7
                },
                "role": "SOLO",
                "lane": "MIDDLE"
            }
        },
        {
            "participantId": 9,
            "teamId": 200,
            "championId": 12,
            "spell1Id": 14,
            "spell2Id": 4,
            "stats": {
                "participantId": 9,
                "win": false,
                "item0": 3907,
                "item1": 3285,
                "item2": 3111,
                "item3": 3194,
                "item4": 3089,
                "item5": 3001,
                "item6": 3340,
                "kills": 12,
                "deaths": 16,
                "assists": 17,
                "largestKillingSpree": 3,
                "largestMultiKill": 1,
                "killingSprees": 3,
                "longestTimeSpentLiving": 626,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 147835,
                "magicDamageDealt": 125450,
                "physicalDamageDealt": 16914,
                "trueDamageDealt": 5471,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 46796,
                "magicDamageDealtToChampions": 39149,
                "physicalDamageDealtToChampions": 2821,
                "trueDamageDealtToChampions": 4825,
                "totalHeal": 25614,
                "totalUnitsHealed": 5,
                "damageSelfMitigated": 117766,
                "damageDealtToObjectives": 13159,
                "damageDealtToTurrets": 2096,
                "visionScore": 37,
                "timeCCingOthers": 87,
                "totalDamageTaken": 79913,
                "magicalDamageTaken": 58167,
                "physicalDamageTaken": 19144,
                "trueDamageTaken": 2602,
                "goldEarned": 22856,
                "goldSpent": 32000,
                "turretKills": 2,
                "inhibitorKills": 0,
                "totalMinionsKilled": 88,
                "neutralMinionsKilled": 18,
                "neutralMinionsKilledTeamJungle": 8,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 260,
                "champLevel": 18,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 20,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 6,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8112,
                "perk0Var1": 2562,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8126,
                "perk1Var1": 1973,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8138,
                "perk2Var1": 30,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8135,
                "perk3Var1": 6743,
                "perk3Var2": 5,
                "perk3Var3": 0,
                "perk4": 9111,
                "perk4Var1": 2754,
                "perk4Var2": 580,
                "perk4Var3": 0,
                "perk5": 8014,
                "perk5Var1": 1137,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8000,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 9,
                "creepsPerMinDeltas": {
                    "10-20": 1.2,
                    "0-10": 2.1,
                    "30-end": 1.3,
                    "20-30": 2.9
                },
                "xpPerMinDeltas": {
                    "10-20": 749.8,
                    "0-10": 548.8,
                    "30-end": 730.15,
                    "20-30": 680.9
                },
                "goldPerMinDeltas": {
                    "10-20": 501.6,
                    "0-10": 301.6,
                    "30-end": 457.75,
                    "20-30": 466.5
                },
                "csDiffPerMinDeltas": {
                    "10-20": -1.1,
                    "0-10": -0.8500000000000001,
                    "30-end": -2.725,
                    "20-30": 0.29999999999999993
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -53.19999999999993,
                    "0-10": -34.900000000000006,
                    "30-end": -175.975,
                    "20-30": -83.2000000000001
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1501.1999999999998,
                    "0-10": 843.9000000000001,
                    "30-end": 1949.55,
                    "20-30": 1747.1
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 384.75,
                    "0-10": 427.75000000000006,
                    "30-end": 645.3,
                    "20-30": 363.2500000000001
                },
                "role": "DUO",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 10,
            "teamId": 200,
            "championId": 12,
            "spell1Id": 4,
            "spell2Id": 14,
            "stats": {
                "participantId": 10,
                "win": false,
                "item0": 3285,
                "item1": 3089,
                "item2": 3151,
                "item3": 3111,
                "item4": 3194,
                "item5": 3100,
                "item6": 3363,
                "kills": 13,
                "deaths": 13,
                "assists": 22,
                "largestKillingSpree": 4,
                "largestMultiKill": 2,
                "killingSprees": 4,
                "longestTimeSpentLiving": 639,
                "doubleKills": 1,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 158775,
                "magicDamageDealt": 130192,
                "physicalDamageDealt": 20957,
                "trueDamageDealt": 7626,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 33167,
                "magicDamageDealtToChampions": 26383,
                "physicalDamageDealtToChampions": 3615,
                "trueDamageDealtToChampions": 3168,
                "totalHeal": 25520,
                "totalUnitsHealed": 5,
                "damageSelfMitigated": 142899,
                "damageDealtToObjectives": 8251,
                "damageDealtToTurrets": 2491,
                "visionScore": 37,
                "timeCCingOthers": 53,
                "totalDamageTaken": 88435,
                "magicalDamageTaken": 70470,
                "physicalDamageTaken": 16801,
                "trueDamageTaken": 1164,
                "goldEarned": 23543,
                "goldSpent": 29020,
                "turretKills": 1,
                "inhibitorKills": 0,
                "totalMinionsKilled": 77,
                "neutralMinionsKilled": 37,
                "neutralMinionsKilledTeamJungle": 26,
                "neutralMinionsKilledEnemyJungle": 4,
                "totalTimeCrowdControlDealt": 225,
                "champLevel": 18,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 20,
                "wardsKilled": 2,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 6,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8008,
                "perk0Var1": 3,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 9111,
                "perk1Var1": 3313,
                "perk1Var2": 700,
                "perk1Var3": 0,
                "perk2": 9103,
                "perk2Var1": 18,
                "perk2Var2": 20,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 741,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8463,
                "perk4Var1": 991,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8451,
                "perk5Var1": 237,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8400,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5001
            },
            "timeline": {
                "participantId": 10,
                "creepsPerMinDeltas": {
                    "10-20": 2.3,
                    "0-10": 1.5,
                    "30-end": 1.35,
                    "20-30": 1.2
                },
                "xpPerMinDeltas": {
                    "10-20": 924.5,
                    "0-10": 600.3,
                    "30-end": 642.25,
                    "20-30": 742.3
                },
                "goldPerMinDeltas": {
                    "10-20": 560.7,
                    "0-10": 391.6,
                    "30-end": 448.35,
                    "20-30": 404.90000000000003
                },
                "csDiffPerMinDeltas": {
                    "10-20": -1.1,
                    "0-10": -0.8500000000000001,
                    "30-end": -2.725,
                    "20-30": 0.29999999999999993
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -53.19999999999993,
                    "0-10": -34.900000000000006,
                    "30-end": -175.975,
                    "20-30": -83.2000000000001
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1677.5,
                    "0-10": 969.4,
                    "30-end": 2041.15,
                    "20-30": 2114.3
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 384.75,
                    "0-10": 427.75000000000006,
                    "30-end": 645.3,
                    "20-30": 363.2500000000001
                },
                "role": "DUO",
                "lane": "BOTTOM"
            }
        }
    ],
    "participantIdentities": [
        {
            "participantId": 1,
            "player": {
                "platformId": "NA1",
                "accountId": "5cACuGIUVZ9UWfVl7l7Eff6AXJQXAA2zmq90QVSUi3CO9Dw",
                "summonerName": "shadowkami",
                "summonerId": "6B4H2M7t-DtpyS9FEEAP9ZOI7130c94fu0xZYFutyBtckFU",
                "currentPlatformId": "NA1",
                "currentAccountId": "5cACuGIUVZ9UWfVl7l7Eff6AXJQXAA2zmq90QVSUi3CO9Dw",
                "matchHistoryUri": "/v1/stats/player_history/NA1/201297769",
                "profileIcon": 4072
            }
        },
        {
            "participantId": 2,
            "player": {
                "platformId": "NA1",
                "accountId": "fLlJYXEp669LLDfeBtbQPqJHxN7ALZSoBPxABqIi6YzUy3g",
                "summonerName": "BlushedCoinJr",
                "summonerId": "7IkBPwqtCtg4AKvyEv0TDTYY04FKqSDKAP6HDhDXsFFxvhY",
                "currentPlatformId": "NA1",
                "currentAccountId": "fLlJYXEp669LLDfeBtbQPqJHxN7ALZSoBPxABqIi6YzUy3g",
                "matchHistoryUri": "/v1/stats/player_history/NA1/229199400",
                "profileIcon": 4661
            }
        },
        {
            "participantId": 3,
            "player": {
                "platformId": "NA1",
                "accountId": "zxt8JXB8OOpBGfjykKER4zg3kY-OFjg5NlXmTBhvj9ECJJ8",
                "summonerName": "0oWencyo0",
                "summonerId": "10u8OLsTcnm0SGx4LqgZbNtMsiyIzJ3JLsh3lRttDc5S_so",
                "currentPlatformId": "NA1",
                "currentAccountId": "zxt8JXB8OOpBGfjykKER4zg3kY-OFjg5NlXmTBhvj9ECJJ8",
                "matchHistoryUri": "/v1/stats/player_history/NA1/211789176",
                "profileIcon": 4497
            }
        },
        {
            "participantId": 4,
            "player": {
                "platformId": "NA1",
                "accountId": "oSVrcIOrRGaIVTbtxZT9T0o8D2bt6dvhyrF6bONP2AulC5Y",
                "summonerName": "0oWendyo0",
                "summonerId": "ygBxVt0nMFP6a5Fq_2seQnS_PvdYxloeUmMjem8pupGecBg",
                "currentPlatformId": "NA1",
                "currentAccountId": "oSVrcIOrRGaIVTbtxZT9T0o8D2bt6dvhyrF6bONP2AulC5Y",
                "matchHistoryUri": "/v1/stats/player_history/NA1/229256659",
                "profileIcon": 4589
            }
        },
        {
            "participantId": 5,
            "player": {
                "platformId": "NA1",
                "accountId": "Ey87op0XxAmKlyNxzBNsunIj0HVUViHxmmzE2OaqyN51oQ",
                "summonerName": "zhangtony",
                "summonerId": "Mk3DuvakiGOdwfWC-vlF9jZ9ftbYHHxGiHBXXpbK4TOmiLA",
                "currentPlatformId": "NA1",
                "currentAccountId": "Ey87op0XxAmKlyNxzBNsunIj0HVUViHxmmzE2OaqyN51oQ",
                "matchHistoryUri": "/v1/stats/player_history/NA1/46728131",
                "profileIcon": 4490
            }
        },
        {
            "participantId": 6,
            "player": {
                "platformId": "NA1",
                "accountId": "qFk8dfXla-yUTdnZ_80NFGbLK1JbAHhGymM7G_X3SXZo3Cc",
                "summonerName": "Rezvire",
                "summonerId": "-hFdYozl2w041wonSMUCjnSoluTllNRAFJSHIRQPf8culDc",
                "currentPlatformId": "NA1",
                "currentAccountId": "qFk8dfXla-yUTdnZ_80NFGbLK1JbAHhGymM7G_X3SXZo3Cc",
                "matchHistoryUri": "/v1/stats/player_history/NA1/232142040",
                "profileIcon": 4665
            }
        },
        {
            "participantId": 7,
            "player": {
                "platformId": "NA1",
                "accountId": "7YletAEajEsFr-0mUOp7B6J3uPpa0qlg1tJ6xcCWxAh80FPX6SOeQjhz",
                "summonerName": "Signzs",
                "summonerId": "tMfyFkuihJ2Fb5ANPQlWPbxtGJJNwGvL299bWbagBEHUNrql",
                "currentPlatformId": "NA1",
                "currentAccountId": "7YletAEajEsFr-0mUOp7B6J3uPpa0qlg1tJ6xcCWxAh80FPX6SOeQjhz",
                "matchHistoryUri": "/v1/stats/player_history/NA1/2441035985701344",
                "profileIcon": 23
            }
        },
        {
            "participantId": 8,
            "player": {
                "platformId": "NA",
                "accountId": "schGr0hXJtNvRTejNvlBmN-TAt3taj3IFivWGCXuN6FeWg",
                "summonerName": "Derriere Seepage",
                "summonerId": "WCH5EKOgo37OgSrYbRQ_kDLQ7CD1sA0iELIqLOF5mYUVkLQ",
                "currentPlatformId": "NA1",
                "currentAccountId": "schGr0hXJtNvRTejNvlBmN-TAt3taj3IFivWGCXuN6FeWg",
                "matchHistoryUri": "/v1/stats/player_history/NA/33960102",
                "profileIcon": 4657
            }
        },
        {
            "participantId": 9,
            "player": {
                "platformId": "NA1",
                "accountId": "BJQ0RRXV_0Znamf5pGLuMK0VjpDJBaqzMwUPvP11Ouw9EBI",
                "summonerName": "Swaggy ACE",
                "summonerId": "gFOywcPXeXJ7jyoKblRXmsEKfweiruciF-4XmvxgnvXq1gQ",
                "currentPlatformId": "NA1",
                "currentAccountId": "BJQ0RRXV_0Znamf5pGLuMK0VjpDJBaqzMwUPvP11Ouw9EBI",
                "matchHistoryUri": "/v1/stats/player_history/NA1/213689623",
                "profileIcon": 921
            }
        },
        {
            "participantId": 10,
            "player": {
                "platformId": "NA1",
                "accountId": "XkUZa06Fl6BSonzgkKV6O95nFhMpE39pHORIIfQhu_510TM",
                "summonerName": "Jie Mo",
                "summonerId": "UXoAkTxdlFdU-NkLf6dlUfJHDklhBENbmXq2hZChk9KUTMI",
                "currentPlatformId": "NA1",
                "currentAccountId": "XkUZa06Fl6BSonzgkKV6O95nFhMpE39pHORIIfQhu_510TM",
                "matchHistoryUri": "/v1/stats/player_history/NA1/227816941",
                "profileIcon": 4568
            }
        }
    ]
}


chap = {"Aatrox":
            {
                "version":"10.19.1",
                "id":"Aatrox",
                "key":"266",
                "name":"Aatrox",
                "title":"the Darkin Blade",
                "blurb":"Once honored d...",
                "info":
                    {
                        "attack":8,"defense":4,"magic":3,"difficulty":4
                    },
                "image":
                    {
                        "full":"Aatrox.png","sprite":"champion0.png","group":"champion","x":0,"y":0,"w":48,"h":48
                    },
                "tags":
                    ["Fighter","Tank"],
                "partype":"Blood Well",
                "stats":
                    {
                        "hp":580,
                        "hpperlevel":90,
                        "mp":0,
                        "mpperlevel":0,
                        "movespeed":345,
                        "armor":38,
                        "armorperlevel":3.25,
                        "spellblock":32.1,
                        "spellblockperlevel":1.25,
                        "attackrange":175,
                        "hpregen":3,
                        "hpregenperlevel":1,
                        "mpregen":0,
                        "mpregenperlevel":0,
                        "crit":0,
                        "critperlevel":0,
                        "attackdamage":60,
                        "attackdamageperlevel":5,
                        "attackspeedperlevel":2.5,
                        "attackspeed":0.651
                    }
            }
}